//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon_WebAPI.DomainEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetail
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public string Notes { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
